USE rutas_app;

-- UPDATE con precio incluido para ser más explícito
UPDATE producto SET nombre = 'Bota de Trekking Waterproof Premium', precio = 89.99 WHERE id_producto = 1;
UPDATE producto SET nombre = 'Zapatilla Trail Running Amortiguada', precio = 64.99 WHERE id_producto = 2;
UPDATE producto SET nombre = 'Bota de Alta Montaña Profesional', precio = 179.99 WHERE id_producto = 3;
UPDATE producto SET nombre = 'Sandalia Trekking Casual', precio = 24.99 WHERE id_producto = 4;
UPDATE producto SET nombre = 'Bota Senderismo Infantil', precio = 39.99 WHERE id_producto = 5;
UPDATE producto SET nombre = 'Zapatilla de Aproximación Ligera', precio = 74.99 WHERE id_producto = 6;
UPDATE producto SET nombre = 'Bota Senderismo Ligera y Cómoda', precio = 54.99 WHERE id_producto = 7;
UPDATE producto SET nombre = 'Calcetín Técnico Trekking Grueso', precio = 14.99 WHERE id_producto = 8;
UPDATE producto SET nombre = 'Mochila Senderismo 20L Compacta', precio = 19.99 WHERE id_producto = 9;
UPDATE producto SET nombre = 'Mochila Senderismo 40L Versátil', precio = 59.99 WHERE id_producto = 10;
UPDATE producto SET nombre = 'Mochila Montaña 60L Grande', precio = 89.99 WHERE id_producto = 11;
UPDATE producto SET nombre = 'Mochila de Día Hiking 10L Ultracompacta', precio = 9.99 WHERE id_producto = 12;
UPDATE producto SET nombre = 'Mochila Escalada y Vía Ferrata 22L', precio = 49.99 WHERE id_producto = 13;
UPDATE producto SET nombre = 'Mochila de Hidratación Trail 10L', precio = 34.99 WHERE id_producto = 14;
UPDATE producto SET nombre = 'Mochila Trekking Mujer 30L', precio = 44.99 WHERE id_producto = 15;
UPDATE producto SET nombre = 'Chubasquero Senderismo Impermeable', precio = 49.99 WHERE id_producto = 16;
UPDATE producto SET nombre = 'Forro Polar Trekking 300g Fleece', precio = 34.99 WHERE id_producto = 17;
UPDATE producto SET nombre = 'Pantalón Trekking Convertible a Bermuda', precio = 29.99 WHERE id_producto = 18;
UPDATE producto SET nombre = 'Camiseta Técnica Merino 100% Hombre', precio = 39.99 WHERE id_producto = 19;
UPDATE producto SET nombre = 'Chaqueta Softshell Montaña Windstop', precio = 69.99 WHERE id_producto = 20;
UPDATE producto SET nombre = 'Legging Trekking Mujer Elástico', precio = 19.99 WHERE id_producto = 21;
UPDATE producto SET nombre = 'Poncho Lluvia Ultraligero Plegable', precio = 14.99 WHERE id_producto = 22;
UPDATE producto SET nombre = 'Chaleco Acolchado Down Ligero', precio = 59.99 WHERE id_producto = 23;
UPDATE producto SET nombre = 'Bastones Plegables Trekking Carbono', precio = 44.99 WHERE id_producto = 24;
UPDATE producto SET nombre = 'Bastones Aluminio Telescópicos', precio = 19.99 WHERE id_producto = 25;
UPDATE producto SET nombre = 'Bastón Nórdico Nordic Walking', precio = 24.99 WHERE id_producto = 26;
UPDATE producto SET nombre = 'Frontal LED 200 Lúmenes 3 Modos', precio = 19.99 WHERE id_producto = 27;
UPDATE producto SET nombre = 'Frontal Recargable USB 500 Lúmenes', precio = 49.99 WHERE id_producto = 28;
UPDATE producto SET nombre = 'Linterna Compacta de Mano 250 Lúmenes', precio = 14.99 WHERE id_producto = 29;
UPDATE producto SET nombre = 'Gafas de Sol Polarizadas Montaña', precio = 29.99 WHERE id_producto = 30;
UPDATE producto SET nombre = 'Guantes de Trekking Elasticados', precio = 12.99 WHERE id_producto = 31;
UPDATE producto SET nombre = 'Gorro Merino Trekking Reversible', precio = 16.99 WHERE id_producto = 32;
UPDATE producto SET nombre = 'Braga de Cuello Merino Multifunción', precio = 22.99 WHERE id_producto = 33;
UPDATE producto SET nombre = 'Cinturón Riñonera Running 1L', precio = 9.99 WHERE id_producto = 34;
UPDATE producto SET nombre = 'Arnés de Escalada Regulable', precio = 29.99 WHERE id_producto = 35;
UPDATE producto SET nombre = 'Cuerda Dinámica 10mm x 50m Impermeable', precio = 89.99 WHERE id_producto = 36;
UPDATE producto SET nombre = 'Mosquetón HMS Seguro Automático', precio = 19.99 WHERE id_producto = 37;
UPDATE producto SET nombre = 'Pies de Gato Escalada con Velcro', precio = 49.99 WHERE id_producto = 38;
UPDATE producto SET nombre = 'Casco de Escalada Polivalente', precio = 39.99 WHERE id_producto = 39;
UPDATE producto SET nombre = 'Magnesio Escalada Polvo 200g + Bolsa', precio = 14.99 WHERE id_producto = 40;
UPDATE producto SET nombre = 'Crampones Aluminio 10 Puntas Universal', precio = 34.99 WHERE id_producto = 41;
UPDATE producto SET nombre = 'Tienda de Campaña 2 Personas Igloo', precio = 69.99 WHERE id_producto = 42;
UPDATE producto SET nombre = 'Saco de Dormir 15°C Rectangular', precio = 24.99 WHERE id_producto = 43;
UPDATE producto SET nombre = 'Saco de Dormir Plumón 0°C Momia', precio = 99.99 WHERE id_producto = 44;
UPDATE producto SET nombre = 'Esterilla Autoinflable 3cm Aislante', precio = 39.99 WHERE id_producto = 45;
UPDATE producto SET nombre = 'Hornillo de Gas Ultracompacto', precio = 19.99 WHERE id_producto = 46;
UPDATE producto SET nombre = 'Batería Solar 10000mAh Powerbank', precio = 44.99 WHERE id_producto = 47;
UPDATE producto SET nombre = 'Botella de Agua Tritan 0,8L', precio = 7.99 WHERE id_producto = 48;
UPDATE producto SET nombre = 'Botella Aislante Acero Inoxidable 0,5L', precio = 17.99 WHERE id_producto = 49;
UPDATE producto SET nombre = 'Bolsa de Hidratación Softflask 2L', precio = 14.99 WHERE id_producto = 50;
UPDATE producto SET nombre = 'Pastillas Potabilizadoras 50 Unidades', precio = 9.99 WHERE id_producto = 51;
UPDATE producto SET nombre = 'Filtro de Agua Portátil Fibra Hueca', precio = 29.99 WHERE id_producto = 52;
UPDATE producto SET nombre = 'Botiquín de Primeros Auxilios Compacto', precio = 19.99 WHERE id_producto = 53;
UPDATE producto SET nombre = 'GPS de Mano Portátil con Mapas', precio = 219.99 WHERE id_producto = 54;
UPDATE producto SET nombre = 'Silbato de Emergencia Alta Potencia 100dB', precio = 4.99 WHERE id_producto = 55;
UPDATE producto SET nombre = 'Manta Térmica de Emergencia Isotérmica', precio = 3.99 WHERE id_producto = 56;
UPDATE producto SET nombre = 'Spray Repelente Insectos DEET 50%', precio = 11.99 WHERE id_producto = 57;

-- VERIFICACIÓN
SELECT id_producto, nombre, precio FROM producto WHERE id_producto BETWEEN 1 AND 57 ORDER BY id_producto;